version: "3.7"

services:

  gcs-signed-upload:
    container_name: ${SERVICE_NAME}
    image: ${SERVICE_NAME}:latest
    build: ./
    #read_only: true
    environment:
      - PORT=${PORT}
      - BUCKET=${BUCKET}
    ports:
      - "${PORT}:${PORT}"
